"""Build fixed v0.4 fallback and no-fallback packet fixtures.

The success packet is generated by ``services/run_daily.py``.  This helper
copies that complete v0.4 packet into the two deterministic failure scenarios
used by browser acceptance; it never constructs a legacy single-stage result.
"""

from __future__ import annotations

import copy
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from services.data import packet  # noqa: E402


DATA_DIR = ROOT / "dashboard" / "public" / "data"

LEGACY_FILES = (
    "snapshot.json",
    "series.json",
    "analysis-current.json",
    "analysis-fallback.json",
    "status.json",
    "status-failure.json",
    "status-no-fallback.json",
)


def main() -> int:
    success = packet.load_packet(DATA_DIR / "packet.json")
    if not success or success.get("schema_version") != "0.4.0":
        print("先运行 `python services/run_daily.py --mock-ai` 生成 v0.4.0 成功包")
        return 1

    failure = copy.deepcopy(success)
    failure["run_id"] = f"{success['run_id']}--fixture-failure"
    failure["analysis"] = None
    failure["fallback"] = copy.deepcopy(success.get("analysis"))
    failure["status"] = {
        **success["status"],
        "today_available": False,
        "reason": "今日 AI 分析不可用（验收回退场景）",
    }
    packet.write_packet_atomic(failure, DATA_DIR / "packet-failure.json")
    print(f"wrote packet-failure.json (fallback={bool(failure['fallback'])})")

    no_fallback = copy.deepcopy(failure)
    no_fallback["run_id"] = f"{success['run_id']}--fixture-no-fallback"
    no_fallback["fallback"] = None
    no_fallback["analysis_date"] = None
    no_fallback["status"] = {
        **no_fallback["status"],
        "last_success_date": None,
    }
    packet.write_packet_atomic(no_fallback, DATA_DIR / "packet-no-fallback.json")
    print("wrote packet-no-fallback.json")

    removed = []
    for name in LEGACY_FILES:
        legacy = DATA_DIR / name
        if legacy.exists():
            legacy.unlink()
            removed.append(name)
    if removed:
        print(f"removed legacy scattered files: {', '.join(removed)}")
    print("v0.4.0 fixtures ready")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
